version: '3.7'

services:
  ui:
    image: swaggerapi/swagger-ui:v3.23.8
    ports:
      - '${PORT_UI}:8080'
    depends_on:
      - nginx
    environment:
      - API_URL=http://localhost:${PORT_NGINX}/swagger.yml
  nginx:
    image: nginx:1.17-alpine
    ports:
      - '${PORT_NGINX}:80'
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
