openapi: 3.0.2
info:
  title: My first swagger
  description: It's my first swagger.
  # termsOfService: http://example.com/terms/
  contact:
    name: kaave
    url: http://kaave.github.com
    email: junkjunctions+swagger@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
paths:
  /me:
    get:
      responses:
        '200':
          description: A JSON array of User model
          content:
            application/json: # レスポンスの形式指定
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Me' # 参照するモデル
                example:
                  name: kaave
                  birthday: 1982-09-24
                  gender: male
                  height: 181
                  weight: 68

